### ISSUE TITLE
[博士论文模板] 偶数页面起始位置太靠近页眉

### ISSUE THREAD

**Issue by J6rry** [fredqi/xduthesis#34]
发现偶数页面中，下式内容离页眉比较近，与Word模板不一致，也不是很美观。

**Comment by fredqi** [comment]
"下式内容”？

**Comment by J6rry** [comment]
Sorry，是『下面的内容』，即正文

**Comment by J6rry** [comment]
![screen shot 2015-01-17 at 09 35 45](https://cloud.githubusercontent.com/assets/5556945/5789340/77992ec4-9e2c-11e4-99e3-073cec9180b4.png)
像这样的

**Comment by J6rry** [comment]
老师，这个问题怎么解决呢？后来发现奇数与偶数页都比较靠上。
![image](https://cloud.githubusercontent.com/assets/5556945/6142432/fd756c12-b17b-11e4-8be9-1f2530ecd6b5.png)
