### ISSUE TITLE
[博士论文模板] 插图问题

### ISSUE THREAD

**Issue by J6rry** [fredqi/xduthesis#35]
正常的插入图片是没有问题的。如果插图接近一页的页尾会被自动安排到下一页显示，这时，原来要插图的位置处就会多出一行空行，这个问题可能是由什么原因引起的呢？

**Comment by fredqi** [comment]
论文排版中，图与表是作为浮动体来处理的。图与表的位置在LaTeX中是根据算法计算确定的，通常用户的控制权很少。

更一般的说，引用图表时不要使用“如下图”，“如上表”之类的与位置相关的引用方式，而使用诸如"如图x.y”所示。

新增加的空格与你的文本内容有一定的关系。具体产生的原因还是要看具体的内容。通常不超过两行的空白就没有问题，如果觉得空白比较多，可以调整TeX文件中插图内容与文字内容的位置。

**Comment by J6rry** [comment]
谢谢您，问题已经得到解决了。如果出现多出一行空行可以将上一段最后一个回车删除，这样由TeX自己安排浮动体的位置就不会在原位置留有空行了。
