### ISSUE TITLE
[本科论文模板] xdu@front 无效问题

### ISSUE THREAD

**Issue by huyangGrace** [fredqi/xduthesis#38]
我想让摘要页去除页码，只留页眉页脚，但使用\thispagestyle{xdu@front}命令并不起作用，依然会显示页码和页眉；
为了产生对比，在相同位置我分别用了\thispagestyle{xdu@empty}和\thispagestyle{xdu@headings}
发现都产生预期效果。
由此推断，xdu@front命令是不是不起作用？

**Comment by fredqi** [comment]
摘要页属于LaTeX文档中的前置部分，其页眉页脚格式就是由 `xdu@front` 定义的。所以你使用 `\thispagestyle{xdu@front}` 页眉页脚不发生改变是功能正常的表现。
