### ISSUE TITLE
使用遇到问题

### ISSUE THREAD

**Issue by ldsyou92** [fredqi/xduthesis#44]
齐老师你好，我在使用您的模板的过程中，文档说明中的多个文件都缺失，还有，这套模板有没有说明的文档，一直编译不通过，不知道是哪里出了问题，希望得到您的帮助。

**Comment by ryekee** [comment]
把你的编译环境、报错的信息发上来看看呀，大家才好帮你

**Comment by fredqi** [comment]
没有充分信息，所以关闭。
