### ISSUE TITLE
latex模板问题求助

### ISSUE THREAD

**Issue by zlh004** [fredqi/xduthesis#46]
老师您好。在使用您的latex模板中的参考文献引用的时候，在refs.bib中添加作者时，本身他就是缩写，结果在编译过后被再次缩写。如果我想关闭自动缩写该如何设置呢？
![InkedTIM截图20190427111135_LI](https://user-images.githubusercontent.com/38122569/56844102-73b7d780-68dd-11e9-9a22-7f9a2330ec82.jpg)

**Comment by fredqi** [comment]
作者一行的正确写法是：
`author = {E. H. German},`
注意英文标点符号之后的英文空格，这是英语语法规定必须要有的。

此外，注意不同类型的期刊的写法。

**Comment by zlh004** [comment]
老师，我尝试过打空格，发现是您的模板当中名字默认调序，谢谢老师。
