### ISSUE TITLE
在编译的时候字体报错？

### ISSUE THREAD

**Issue by laetella** [fredqi/xduthesis#47]
LaTeX Warning: You have requested, on input line 4367, version
               `2019/03/15' of package fontspec,
               but only version
               `2017/11/09 v2.6g Font selection for XeLaTeX and LuaLaTeX'
               is available.

("C:\Program Files\MiKTeX 2.9\tex\xelatex\xecjk\xeCJK.cfg"))
! Undefined control sequence.
\xeCJK/family/rm ...e:n \fontspec_gset_family:Nnn 
                                                  \g__xeCJK_fontspec_family_...
l.120 \setCJKsansfont
                     {Adobe Heiti Std}
?

**Comment by fredqi** [comment]
需要自己搜索查询如何安装 Adobe系列中文字体。

http://lazybios.com/2013/05/how-to-use-chinese-fonts-in-latax/
